name: besties_notes
description: " Mobile app for teacher's notes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  image_picker: ^1.2.1
  path: ^1.9.1
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  bloc_lint: ^0.3.5
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true